## Numpy常用数据结构

### 1.数组创建

In [2]:
import numpy as np
arr1 = np.array([-9,8,7,23])
arr1

array([-9,  8,  7, 23])

In [5]:
#尝试改变为int、float或者str
arr2 = np.array([-9,8,7,23],dtype=float)
arr2

array([-9.,  8.,  7., 23.])

In [6]:
arr3 = np.array([[2,4,1,3],[4,6,3,9],[2,5,9,1]])
arr3

array([[2, 4, 1, 3],
       [4, 6, 3, 9],
       [2, 5, 9, 1]])

In [7]:
#使用其它函数创建数组
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones([4,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
#矩阵运算
arr3 +1

array([[ 3,  5,  2,  4],
       [ 5,  7,  4, 10],
       [ 3,  6, 10,  2]])

### 2. 数组方法

In [13]:
arr3

array([[2, 4, 1, 3],
       [4, 6, 3, 9],
       [2, 5, 9, 1]])

In [14]:
#数组维度
arr3.ndim

2

In [15]:
#形状
arr3.shape

(3, 4)

In [16]:
#个数
arr3.size

12

In [17]:
#类型
arr3.dtype

dtype('int64')

In [18]:
#运算
arr3 + 1

array([[ 3,  5,  2,  4],
       [ 5,  7,  4, 10],
       [ 3,  6, 10,  2]])

In [19]:
arr3 / 2

array([[1. , 2. , 0.5, 1.5],
       [2. , 3. , 1.5, 4.5],
       [1. , 2.5, 4.5, 0.5]])

In [21]:
data2 = ((3,5,2.4,3),(4,7,2.9,8),(8,3,6,7.8),(2.3,5.6,2.5,1.9))
arr4 = np.array(data2)
arr4

array([[3. , 5. , 2.4, 3. ],
       [4. , 7. , 2.9, 8. ],
       [8. , 3. , 6. , 7.8],
       [2.3, 5.6, 2.5, 1.9]])

In [22]:
#访问——行索引
arr4[2]

array([8. , 3. , 6. , 7.8])

In [26]:
#访问——多行
arr4[0:3]

array([[3. , 5. , 2.4, 3. ],
       [4. , 7. , 2.9, 8. ],
       [8. , 3. , 6. , 7.8]])

In [25]:
#访问——多列
arr4[:,1:3]

array([[5. , 2.4],
       [7. , 2.9],
       [3. , 6. ],
       [5.6, 2.5]])

In [27]:
#访问——多行多列切片
arr4[1:,2:]

array([[2.9, 8. ],
       [6. , 7.8],
       [2.5, 1.9]])

In [23]:
#访问值——行索引,列索引
arr4[2,1]

3.0

In [28]:
arr4[2][1]

3.0

### 3.Numpy常用数据清洗函数
- 排序：sort
- 降序：sorted

In [31]:
s = np.array([2,5,1,5,7.8,1,4,7,3,9,7])

In [32]:
#排序
np.sort(s)

array([1. , 1. , 2. , 3. , 4. , 5. , 5. , 7. , 7. , 7.8, 9. ])

In [33]:
#降序
sorted(s,reverse=True)

[9.0, 7.8, 7.0, 7.0, 5.0, 5.0, 4.0, 3.0, 2.0, 1.0, 1.0]

In [34]:
arrn = np.array([[0,1,3],[4,2,9],[4,5,9],[1,-3,4]])
arrn

array([[ 0,  1,  3],
       [ 4,  2,  9],
       [ 4,  5,  9],
       [ 1, -3,  4]])

In [37]:
#默认排序
np.sort(arrn)

array([[ 0,  1,  3],
       [ 2,  4,  9],
       [ 4,  5,  9],
       [-3,  1,  4]])

In [36]:
#定行还是列方向,0-行，1-列
np.sort(arrn,axis=0)

array([[ 0, -3,  3],
       [ 1,  1,  4],
       [ 4,  2,  9],
       [ 4,  5,  9]])

In [38]:
np.sort(arrn,axis=1)

array([[ 0,  1,  3],
       [ 2,  4,  9],
       [ 4,  5,  9],
       [-3,  1,  4]])

- argsort返回的是排完序以后，在原数据中的索引位置
- 返回的是数据中,从小到大的索引值

In [40]:
#1最小，对应索引值0，8最大，对应索引值13
s = np.array([1,2,3,4,3,1,2,2,4,6,7,2,4,8,4,5])
np.argsort(s)

array([ 0,  5,  1,  6,  7, 11,  2,  4,  3,  8, 12, 14, 15,  9, 10, 13])

- np.where和np.extract

In [41]:
#满足条件的，赋值为3，不满足的赋值为-1，返回的数据长度和s一样
np.where(s>3,1,-1)

array([-1, -1, -1,  1, -1, -1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1])

- np.extract 只会输出满足条件的数据

In [42]:
np.extract(s>3,s)

array([4, 4, 6, 7, 4, 8, 4, 5])

## Pandas常用数据结构

#### series序列

In [43]:
import pandas as pd
import numpy as np

In [48]:
#构造序列
series1 = pd.Series([2.8,3.01,8.99,8.59,5.18])
series2 = pd.Series([2.8,3.01,8.99,8.59,5.18],index=('a','b','c','d','e'),name='这是一个series')
series3 = pd.Series({'北京':9.8,'上海':9.7,'广州':9.5})

In [50]:
series1

0    2.80
1    3.01
2    8.99
3    8.59
4    5.18
dtype: float64

In [52]:
series2

a    2.80
b    3.01
c    8.99
d    8.59
e    5.18
Name: 这是一个series, dtype: float64

In [53]:
series3

北京    9.8
上海    9.7
广州    9.5
dtype: float64

In [54]:
#series方法
series2.values

array([2.8 , 3.01, 8.99, 8.59, 5.18])

In [55]:
#索引
series3.index

Index(['北京', '上海', '广州'], dtype='object')

#### DataFrame

In [60]:
#构造数据框；数据框就是一个二维表结构，数据分析中常用的数据结构
list1 = [['张三',23,'男'],['里斯',18,'女'],['王五',25,'男']]
dff1 = pd.DataFrame(list1,columns=['姓名','年龄','性别'])
dff1

姓名  年龄 性别
0  张三  23  男
1  里斯  18  女
2  王五  25  男

In [61]:
type(dff1)

pandas.core.frame.DataFrame

In [63]:
dff2 = pd.DataFrame({'姓名':['张三','里斯','王五'],'':[23,18,25],'年龄':['男','女','男']}) 
dff2

姓名     年龄
0  张三  23  男
1  里斯  18  女
2  王五  25  男

In [65]:
array1 = np.array([['张三',23,'男'],['里斯',18,'女'],['王五',25,'男']])
dff3 = pd.DataFrame(array1,columns=['姓名','年龄','性别'],index=['a','b','c'])
dff3

姓名  年龄 性别
a  张三  23  男
b  里斯  18  女
c  王五  25  男

- dataframe方法

In [72]:
#值
dff3.values

array([['张三', '23', '男'],
       ['里斯', '18', '女'],
       ['王五', '25', '男']], dtype=object)

In [73]:
#索引
dff3.index

Index(['a', 'b', 'c'], dtype='object')

In [75]:
#列标签
dff3.columns

Index(['姓名', '年龄', '性别'], dtype='object')

In [76]:
#类型
dff3.dtypes

姓名    object
年龄    object
性别    object
dtype: object

In [77]:
#维度
dff3.ndim

2

In [78]:
#个数
dff3.size

9